### ISSUE TITLE
2D RealSFS FST takes another scaffold when no position is found in one of the populations

### ISSUE THREAD

**Issue by clairemerot** [ANGSD/angsd#200]
Hello,
I'm facing an issue with realSFS (fst index) when calculating FST between two populations. When one scaffold has no position in one of the two populations (which happen for short scaffold or with stringent filters), realSFS uses another scaffold instead.

the first command (echo "calcualte the 2dsfs priors"
		realSFS) has no problem skipping the scaffold 
*log
 -> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
	-> Chromosome: 'scaffold1052' does not exists in population: 06_saf_maf_by_pop/BB/BB_maf0.05_pctind0.2.saf.idx **will skip it**
	-> Is in multi sfs, will now read data from chr:scaffold1053

but the second command (echo " prepare the fst for easy window analysis etc"
		realSFS fst index ) says it will skip it and instead it does the calculation on the first scaffold (LG1) which has already been done earlier

*log
-> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
	-> Chromosome: 'scaffold1052' does not exists in population: 06_saf_maf_by_pop/BB/BB_maf0.05_pctind0.2.saf.idx **will skip it**
	-> **Is in multi sfs, will now read data from chr:LG1**
	-> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
	-> Sites to keep[LG1] from pop0:	1303955
	-> Sites to keep[LG1] from pop1:	1303955

Is there any way I should adjust my commands or my files to avoid that problem?
I see that this has already been raised here (https://github.com/ANGSD/angsd/issues/126) but I found no answer to it (please forgive me if I missed something). 

Thanks for your attention, 
and thanks a lot for the very useful angsd and its well-documented wiki!

Claire Mérot

**Comment by ANGSD** [comment]
Thanks for you input and sorry for the delay, there was indeed a problem that was resolved int his commit:

For completeness i used the code below for validating. Feel free to reopen if needed, and thank you very much for taking your time to report this problem.

Best
head -n9 list >pop1.list
tail list >pop2.list
seq 1 3 >rg1
seq 2 4 >rg2
./angsd -b pop1.list -rf rg1 -dosaf 1 -gl 1 -anc ../hs37d5.fa -out pop1
./angsd -b pop2.list -rf rg2 -dosaf 1 -gl 1 -anc ../hs37d5.fa -out pop2
./misc/realSFS pop1.saf.idx pop2.saf.idx >prior
./misc/realSFS fst index pop1.saf.idx pop2.saf.idx -sfs prior -fstout here
./misc/realSFS fst print here.fst.idx |cut -f1|uniq -c

**Comment by clairemerot** [comment]
Hello,
Thanks a lot for having fixed this problem so fast.

 I thought it was all sorted because realSFS was not giving the strange message reported above (coming back to LG1 when one scaffold was missing). Yet, when I looked at the Fst plots by sliding windows, I realized that the bug was still here and that short scaffolds without positions in common between the two populations were replaced by the 1st LG, and then the second LG, etc.... I wonder whether this happen at the stage of the sliding window analysis? 

I can deal with that in post-analyses (I can easily remove scaffolds which longer than expected) so this is not a big issue yet I wonder whether this could be a more important problem for people with fragmented genomes and this slowers the calculation. 

The script i am using is here https://github.com/clairemerot/angsd_pipeline/blob/master/01_scripts/07_fst_by_pop_pair.sh
Feel free to let me know how i can help sorting that.

And thanks a lot for continuously improving angsd, this is a great tool!
Claire

**Comment by ab08028** [comment]
Hi There!
Has there been any progress on Claire's second comment above? Did the bug fix of Feb 22 actually fix the issue, or has her observation of it still occurring been verified? I am running into similar problems when calculating the .idx files a glf file, even using the latest build of ANGSD that has the Feb 22 bug fix.

Are there limits on chromosome/scaffold names in ANGSD? My scaffold names have either underscores or "."s in them, which I worry may also be disrupting ANGSD.

The sort of errors I'm getting are:
When trying to carry out -dosaf from a beagle format file: 
"Problem finding chr:ScbS9RH from faifile  " (the full scaffold format is ScbS9RH_##### where ##### is a number, e.g. ScbS9RH_24292)

When trying to carry out dosaf from a glf format file:
"Trying to access fasta efter end of chromsome+200:ScbS9RH_24292/ScbS9RH_24292 pos=5595049 ref_len=1586"

In a separate set of analyses, this happens with scaffolds that have a different naming convention: 
"Trying to access fasta efter end of chromsome+200:GL896898.1/GL896898.1 pos=53721549 ref_len=52375790"

I've already checked that the .fai length of the scaffold matches the bam header length of the scaffold, which matches the ref_len given in the error above

Worryingly, angsd -dosaf still outputs the .idx file despite the errors which can be converted to an SFS, but it is only for the length of that first scaffold ScbS9RH_24292 (1586 sites) rather than for the whole genome, which is a scary behavior since it makes it harder to catch errors compared to Claire's sliding windows. 

My reference genomes have many small scaffolds, some of which don't have any reads mapping to them since I'm using exome-capture data.

Am I seeing the same sorts of errors as Claire and others? Or is there something else going on?

Thanks so much for your help!

~ Annabel

**Comment by ANGSD** [comment]
Hi I am going through the github issues and I dont seem to be able to replicate.
See the example below, the files are artificial dummy files made just for this scenario.
p1 contains the chrs 1,2,3 p2 only 1,3

./realSFS print p1.saf.idx 2>/dev/null
1	1	0.100000	0.100000	0.100000	-inf	-inf	-inf	-inf
1	2	-inf	0.200000	0.200000	0.200000	-inf	-inf	-inf
1	3	-inf	-inf	0.300000	0.300000	0.300000	-inf	-inf
2	1	0.110000	0.110000	0.100000	-inf	-inf	-inf	-inf
2	2	-inf	0.220000	0.220000	0.200000	-inf	-inf	-inf
2	3	-inf	-inf	0.330000	0.330000	0.330000	-inf	-inf
3	1	0.111000	0.111100	0.111000	-inf	-inf	-inf	-inf
3	2	-inf	0.222000	0.222000	0.222000	-inf	-inf	-inf
3	3	-inf	-inf	0.333000	0.333000	0.333000	-inf	-inf
./realSFS print p2.saf.idx 2>/dev/null
1	1	-0.100000	-0.100000	-0.100000	-inf	-inf	-inf	-inf
1	2	-inf	-0.200000	-0.200000	-0.200000	-inf	-inf	-inf
1	3	-inf	-inf	-0.300000	-0.300000	-0.300000	-inf	-inf
3	1	-0.111000	-0.111100	-0.111000	-inf	-inf	-inf	-inf
3	3	-inf	-inf	-0.333000	-0.333000	-0.333000	-inf	-inf
./realSFS print p1.saf.idx p2.saf.idx 2>/dev/null
1	1	0.100000	0.100000	0.100000	-inf	-inf	-inf	-inf	-0.100000	-0.100000	-0.100000	-inf	-inf	-inf	-inf
1	2	-inf	0.200000	0.200000	0.200000	-inf	-inf	-inf	-inf	-0.200000	-0.200000	-0.200000	-inf	-inf	-inf
1	3	-inf	-inf	0.300000	0.300000	0.300000	-inf	-inf	-inf	-inf	-0.300000	-0.300000	-0.300000	-inf	-inf
3	1	0.111000	0.111100	0.111000	-inf	-inf	-inf	-inf	-0.111000	-0.111100	-0.111000	-inf	-inf	-inf	-inf
3	3	-inf	-inf	0.333000	0.333000	0.333000	-inf	-inf	-inf	-inf	-0.333000	-0.333000	-0.333000	-inf	-inf
