### ISSUE TITLE
Unable to generate vcf file: Segmentation fault

### ISSUE THREAD

**Issue by srachita** [ANGSD/angsd#275]
Hi,
I have been trying to generate vcf file using the following command: angsd -b bam.filelist -dovcf 1 -gl 1 -dopost 1 -domajorminor 1 -domaf 1 -snp_pval 1e-6, but I get the following error
	-> angsd version: 0.930 (htslib: 1.9-362-g9d2163a-dirty) build(Sep 23 2019 13:29:14)
	-> No '-out' argument given, output files will be called 'angsdput'
	-> SNP-filter using a pvalue: 1.000000e-06 correspond to 23.928127 likelihood units
[bammer_main] 32 samples in 32 input files
	-> Parsing 32 number of samples 
[shared.cpp.changeChr():281] refid:0
Charnge chr:0
Segmentation fault
Can someone help me with this? 
Thank you

**Comment by Jungal10** [comment]
The first lines (starting with "->" are just messages/warnings)
The segmentation fault can happen due to lack of memory or you might be that you are pointing to a location that angsd is not able to find. (Check your bam file list to see if all files are correctly listed. Try to include absolute paths as well)

**Comment by srachita** [comment]
Thank you for your quick response. I checked the path of all the bam files I provided and they seem not to be the source of error. Also, I am using a machine with 200gb RAM. Is it too less for this program? Also, I have generated other files using angsd (beagle file) using the same system.

**Comment by ANGSD** [comment]
Does the segfauls also happen if you leave out the -dovcf 1?

Best

**Comment by srachita** [comment]
No there is no such error if I leave out -dovcf 1

**Comment by TeresaPegan** [comment]
This is also happening to me, and I also get no error when I leave out -dovcf 1. Here is the code I'm using:
./angsd -b bam.list -dovcf 1 -gl 1 -dopost 1 -domajorminor 1 -domaf 1 -snp_pval 1e-6

and here is what I get:

[bammer_main] 6 samples in 6 input files
        -> Parsing 6 number of samples 
Segmentation fault: 11


I get this message almost immediately after I run the code. I've checked my file paths and I'm using a machine with a lot of RAM.

Thanks for any help!

**Comment by jordanbemmels** [comment]
Did anyone determine what was the source of error and how to fix it? I also get the same error:

1) command without -dovcf 1 flag --> works fine
2) exact same command but now including -dovcf 1 flag  --> segmentation fault

Thank you!

**Comment by ANGSD** [comment]
Hi sorry about this, I redid the filereading and forgot to comment on these issues list. I removed -dovcf, and made the program output bcf with -dobcf 1. It should be more robust.

I am closing this issue since it should be resolved. Again I am sorry that I forgot to comment on the issue.

**Comment by silastittes** [comment]
After some trial and error,  got the command to work with

**Comment by z0on** [comment]
Hi @ANGSD - I am sorry but I am still having the problem with -doBcf leading to segmentation fault (same deal, immediate segmentation fault when -doBcf option is included, but no problem if it is not included)
tried 
angsd 0.935-33-g79d9455 (htslib 1.12-34-g2b68267)
angsd 0.923 (htslib 1.9)
same thing.

**Comment by z0on** [comment]
good news: Nate Pope's branch seems to be free of this problem
git clone -b nspope_bandedDP https://github.com/ANGSD/angsd.git

**Comment by ANGSD** [comment]
Hi sorry about the delay, it is on the roadmap to merge this branch into the master branch, things has just been dragging out a bit with updating testfiles.

There should be no functional difference with regards to writing bcf.
